[versions]
accompanist = "0.32.0" # https://github.com/google/accompanist/releases
activity = "1.8.2" # https://developer.android.com/jetpack/androidx/releases/activity
android-gradle-plugin = "8.2.2" # https://developer.android.com/build/releases/gradle-plugin
appcompat = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/appcompat
coil-compose = "2.5.0" # https://github.com/coil-kt/coil/releases
compile-target-sdk = "34"
compose-bom = "2024.02.00" # https://developer.android.com/jetpack/compose/bom/bom-mapping
compose-compiler = "1.5.8" # https://developer.android.com/jetpack/androidx/releases/compose-compiler
constraintlayout = "2.1.4" # https://developer.android.com/jetpack/androidx/releases/constraintlayout
constraintlayout-compose = "1.0.1" # https://developer.android.com/jetpack/androidx/releases/constraintlayout
coordinatorlayout = "1.2.0" # https://developer.android.com/jetpack/androidx/releases/coordinatorlayout
coroutines = "1.7.3" # https://github.com/Kotlin/kotlinx.coroutines/releases
datastore = "1.0.0" # https://developer.android.com/jetpack/androidx/releases/datastore
espresso = "3.5.1" # https://developer.android.com/jetpack/androidx/releases/test
firebase-bom = "32.7.1" # https://firebase.google.com/support/release-notes/android#compare-bom-versions
fragment = "1.6.2" # https://developer.android.com/jetpack/androidx/releases/fragment
google-services = "4.4.0"
hilt = "2.50" # https://github.com/google/dagger/releases
junit = "1.1.5" # https://developer.android.com/jetpack/androidx/releases/test
kotlin = "1.9.22" # https://kotlinlang.org/docs/releases.html
kotlinx-serialization = "1.6.2" # https://github.com/Kotlin/kotlinx.serialization/releases
ksp = "1.9.22-1.0.17" # https://github.com/google/ksp/releases
ktlint = "12.1.0" # https://github.com/JLLeitschuh/ktlint-gradle/releases
lifecycle = "2.7.0" # https://developer.android.com/jetpack/androidx/releases/lifecycle
media3 = "1.2.1" # https://developer.android.com/jetpack/androidx/releases/media3
min-sdk = "26"
mockito = "5.3.0" # https://github.com/mockito/mockito-kotlin/releases
navigation = "2.7.7"
okhttp = "4.12.0"
oss-licenses-plugin = "0.10.6" # https://github.com/google/play-services-plugins/releases
paging = "3.2.1" # https://developer.android.com/jetpack/androidx/releases/paging
play-core = "1.8.1"
play-services-oss-licenses = "17.0.1"
protobuf = "3.25.2"
protobuf-plugin = "0.9.4"
recyclerview = "1.3.2"
retrofit2-kotlinx-serialization-converter = "1.0.0"
robolectric = "4.11.1"
room = "2.6.1"
rxandroid = "3.0.2"
rxjava = "3.1.8"
test-core-ktx = "1.5.0"
test-rules = "1.5.0"
test-runner = "1.5.2"
viewpager2 = "1.0.0"

[libraries]
accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version.ref = "accompanist" }
accompanist-placeholder-material3 = { group = "com.google.accompanist", name = "accompanist-placeholder-material3", version.ref = "accompanist" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
animation = { group = "androidx.compose.animation", name = "animation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
espresso-web = { group = "androidx.test.espresso", name = "espresso-web", version.ref = "espresso" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
foundation = { group = "androidx.compose.foundation", name = "foundation" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "google-services" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
idling-concurrent = { group = "androidx.test.espresso.idling", name = "idling-concurrent", version.ref = "espresso" }
junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-reactivestreams-ktx = { group = "androidx.lifecycle", name = "lifecycle-reactivestreams-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
material = { group = "androidx.compose.material", name = "material" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
material3 = { group = "androidx.compose.material3", name = "material3" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-safe-args-gradle-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
okhttp-urlconnection = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" } # for CookieJar
oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "oss-licenses-plugin" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
play-core-ktx = { group = "com.google.android.play", name = "core-ktx", version.ref = "play-core" }
play-services-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "play-services-oss-licenses" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
retrofit2-kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinx-serialization-converter" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core-ktx" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }

[plugins]
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin" }
com-android-application = { id = "com.android.application" }
google-services = { id = "com.google.gms.google-services" }
kotlin-android = { id = "kotlin-android" }
kotlin-parcelize = { id = "kotlin-parcelize" }
kotlin-serialization = { id = "plugin.serialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
oss-licenses-plugin = { id = "com.google.android.gms.oss-licenses-plugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
